{% include 'header.phtml' %}
<div class="container" style="padding: 20px;">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-1">
            <div class="row">
                <h3 class="col-lg-6">Login</h3>
            </div>
            <form class="form-horizontal" action"/login.php">
                <div class="row">
                    <div class="row margin-bottom">
                        <div class="col-lg-4">
                            <label class="form-control-static">Username</label>
                        </div>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="username">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="row margin-bottom">
                        <div class="col-lg-4">
                            <label class="form-control-static">Password</label>
                        </div>
                        <div class="col-lg-8">
                            <input class="form-control" type="password" name="password">
                        </div>
                    </div>
                </div>
                <div class="row ">
                    <div class="col-lg-5 col-lg-offset-5">
                        <input type="submit" class="form-control" value="Log in">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-lg-offset-1">
            <div class="row">
                <h3 class="col-lg-12">Create new account</h3>
            </div>
            <!-- <form class="form-horizontal" action"/account?page=create_account" method="post"> -->
            <form class="form-horizontal" action"createAccount.php" method="POST">
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Username</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="username">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Password</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="password" name="password">
                    </div>
                </div>
                <div class="row margin-bottom-large">
                    <div class="col-lg-4">
                        <label class="form-control-static">Confirm passwords</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="password" name="passwordConfirm">
                    </div>
                </div>
                <!-- ------------------------------------------------------------ -->
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">First Name</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="firstName">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Last Name</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="lastName">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Address 1</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="address1st">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Address 2</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="address2nd">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Town</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="town">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">County</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="county">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Postcode</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="postcode">
                    </div>
                </div>
                <div class="row margin-bottom">
                    <div class="col-lg-4">
                        <label class="form-control-static">Phone</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="phone">
                    </div>
                </div>
                <div class="row margin-bottom-large">
                    <div class="col-lg-4">
                        <label class="form-control-static">Country</label>
                    </div>
                    <div class="col-lg-8">
                        {% include 'countries.phtml' %}
                    </div>
                </div>
                <div class="row ">
                    <div class="col-lg-5 col-lg-offset-5">
                        <input type="submit" class="form-control" value="Create">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
