
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge" /> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ static }}/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
    <!-- <script src="https://www.paypalobjects.com/api/checkout.js"></script> -->
    <script src="{{ static }}/cookie.js"></script>
    <script src="{{ static }}/password.js"></script>
</head>

<body>
<div class="row header">
    <div class="col-md-2 col-sm-1 col-xs-12 icon-center" style="text-align:center">
        <img src="{{ media }}/logo.png">
    </div>
    <div class="col-md-1 col-md-push-8 col-sm-2 col-sm-push-7 hidden-xs icon-center header-link">
        <div class="row">
            <a href="/account.php"><img  src="{{ media }}/user.png"></a>
        </div>
        <div class="row">
            <a href="/account.php"><p>Account</p></a>
        </div>
    </div>
    <div class="col-md-1 col-md-push-8 col-sm-1 col-sm-push-7 hidden-xs icon-center header-link">
        <div class="row">
            <a href="/basket.php"><img  src="{{ media }}/basket.png"></a>
        </div>
        <div class="row">
            <a href="/basket.php">
                <p id="header-subtotal">
                    {% if subTotal > 0 %}
                        &pound{{ subTotal }}
                    {% else %}
                        Basket
                    {% endif %}
                </p>
            </a>
        </div>
    </div>
    <div class="col-md-8 col-md-pull-2 col-sm-7 col-sm-pull-2 col-xs-12 icon-center">
        <form class="search-vcenter" action="/" method="get">
            <input class="form-control search-bar"
                   type="text"
                   name="s"
                   placeholder="Search..">
        </form>
    </div>
</div>
<div class="row menu">
    <div class="col-sm-2 col-xs-4 header-link"><a href="/">Home</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/products/pokemon">Pokemon</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/products/MTG">Magic</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/products/acce">Accessories</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/#">New</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/#">Sale</a></li></div>
</div>
<div class="row menu">
    <div class="hidden-lg hidden-md hidden-sm col-xs-6 header-link"><a href="/account.php"><p>Account</p></a></div>
    <div class="hidden-lg hidden-md hidden-sm col-xs-6 header-link">
        <a href="/basket.php">
            <p id="header-subtotal2">
                {% if subTotal > 0 %}
                    Basket: &pound{{ subTotal }}
                {% else %}
                    Basket
                {% endif %}
            </p>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-ld-12 error">{{ error }}</div>
</div>
