<div class="page-header">
    <img class="logo" src="media/logo.png">
    <div class="user-tools">
        <img class="item" src="media/user.png">
        <img class="item" src="media/basket.png">
    </div>
</div>
<ul class="menu">
    <li><a class="menu-item" href="#">Home</a></li>
    <li><a class="menu-item" href="#">Pokemon</a></li>
    <li><a class="menu-item" href="#">Magic</a></li>
    <li><a class="menu-item" href="#">New</a></li>
    <li><a class="menu-item" href="#">Sale</a></li>
</ul>
