<div class="row header">
    <div class="col-md-2 col-sm-2 col-xs-12 icon-center" style="text-align:center">
        <img src="media/logo.png">
    </div>
    <div class="col-md-1 col-md-push-8 col-sm-1 col-sm-push-8 hidden-xs icon-center header-link">
        <div class="row">
            <a href="#"><img  src="media/user.png"></a>
        </div>
        <div class="row">
            <a href="#"><p>Account</p></a>
        </div>
    </div>
    <div class="col-md-1 col-md-push-8 col-sm-1 col-sm-push-8 hidden-xs icon-center header-link">
        <div class="row">
            <a href="#"><img  src="media/basket.png"></a>
        </div>
        <div class="row">
            <a href="/basket.php"><p>&pound{{ subTotal }}</p></a>
        </div>
    </div>
    <div class="col-md-8 col-md-pull-2 col-sm-8 col-sm-pull-2 col-xs-12 icon-center">
        <form class="search-vcenter">
            <input class="form-control search-bar" type="text" name="search" placeholder="Search..">
        </form>
    </div>
</div>
<div class="row menu">
    <div class="col-sm-2 col-xs-4 header-link"><a href="/?s=">Home</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/?s=pokemon">Pokemon</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/?s=MTG">Magic</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/?s=acce">Accessories</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/#">New</a></li></div>
    <div class="col-sm-2 col-xs-4 header-link"><a href="/#">Sale</a></li></div>
</div>
<div class="row menu">
    <div class="hidden-lg hidden-md hidden-sm col-xs-6 header-link"><a href="#"><p>Account</p></a></div>
    <div class="hidden-lg hidden-md hidden-sm col-xs-6 header-link">
        <a href="/basket.php">
            <p id="basket">
                {% if subTotal %}
                    Basket: &pound{{ subTotal }}
                {% else %}
                    Basket
                {% endif %}
            </p>
        </a>
    </div>
</div>
